### ISSUE TITLE
Please write the mono version required to README

### ISSUE THREAD

**Issue by chakku000** [callmekohei/deopletefs#3]
This plugin doesn't work in the following environment,
- ubuntu18.04
- mono version 4.6.2

and the plugin `deoplete-fsharp` doesn't work.

I confirmed that this plugin works with the mono version 5.18.1.0.

If possible, please specify the version of mono this requires.

**Comment by callmekohei** [comment]
Hello!

Thank you for your advice!

I'll do it.

Just a moment :-)

**Comment by callmekohei** [comment]
Hello !
I do check mono version for deopletefs.

`deopletefs` is available over Mono version 5.4.0.

So I write it on `Readme`.

![Screen Shot 2019-04-05 at 17 02 25](https://user-images.githubusercontent.com/17691683/55620051-f06efe80-57d4-11e9-885a-1e16a43fcc0c.png)


I'll close this issue. :-)
